name: AutoRebase
on:
  push:
    branches-ignore:
      # Ignore branches automatically created by github-rebase
      - rebase-pull-request**
      - cherry-pick-rebase-pull-request**
  pull_request:
    types: [ labeled ]

jobs:
  auto-rebase:
    name: AutoRebase
    runs-on: ubuntu-20.04
    steps:
      - uses: Label305/AutoRebase@v0.1
        with:
          github_token: ${{ secrets.AUTOREBASE_TOKEN }}